//Base de datos en MySQL Workbench

CREATE DATABASE medicamentos;
  use medicamentos;
CREATE TABLE medicamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(500) NOT NULL
);
CREATE TABLE descripciones_medicamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(1000) NOT NULL,
    medicamento_id INT,
    FOREIGN KEY (medicamento_id) REFERENCES medicamentos(id)
);
-- Nombres de medicamentos
INSERT INTO medicamentos (nombre)
VALUES
    ("Aciclovir"),
    ("Acetaminofén"),
    ("Amoxicilina"),
    ("Acetilcisteína"),
    ("Ácido ascórbico"),
    ("Ácido fólico"),
    ("Ácido valproico"),
    ("Albendazol"),
    ("Albuterol"),
    ("Alprazolam"),
    ("Amoxicilina/clavulánico"),
    ("Ampicilina"),
    ("Amiodarona"),
    ("Azitromicina"),
    ("Betametasona"),
    ("Cefotaxima"),
    ("Ceftriaxona"),
    ("Ciprofloxacino"),
    ("Dexametasona"),
    ("Diclofenaco"),
    ("Digoxina"),
    ("Dapsona"),
    ("Diazepam"),
    ("Diclofenaco/misoprostol"),
    ("Digoxina"),
    ("Dobutamina"),
    ("Enalapril"),
    ("Etonogestrel"),
    ("Fenobarbital"),
    ("Fluconazol"),
    ("Fluvoxamina"),
    ("Gabapentina"),
    ("Glibenclamida"),
    ("Glipizida"),
    ("Heparina"),
    ("Ibuprofeno"),
    ("Imipramina"),
    ("Insulina"),
    ("Levofloxacino"),
    ("Loratadina"),
    ("Metformina"),
    ("Metoprolol"),
    ("Morfina"),
    ("Naproxeno"),
    ("Nifedipina"),
    ("Omeprazol"),
    ("Paracetamol"),
    ("Prednisona"),
    ("Propranolol"),
    ("Rifampicina"),
    ("Salbutamol"),
    ("Sertralina"),
    ("Simvastatina"),
    ("Teofilina"),
    ("Valproato"),
    ("Warfarina"),
    ("Zoloft"),
    ("Lorazepam"),
    ("Losartán"),
    ("Metronidazol"),
    ("Ondansetrón"),
    ("Paroxetina"),
    ("Ranitidina"),
    ("Salmeterol"),
    ("Tamsulosina"),
    ("Venlafaxina"),
    ("Xarelto"),
    ("Yasmin"),
    ("Zopiclona"),
    ("Amitriptilina"),
    ("Bromazepam"),
    ("Clonazepam"),
    ("Dextrometorfano"),
    ("Esomeprazol"),
    ("Furosemida"),
    ("Gentamicina"),
    ("Hidroclorotiazida"),
    ("Itraconazol"),
    ("Ketorolaco"),
    ("Lansoprazol"),
    ("Metronidazol"),
    ("Naproxeno"),
    ("Olanzapina"),
    ("Pantoprazol"),
    ("Quetiapina"),
    ("Risperidona"),
    ("Sildenafil"),
    ("Tadalafilo"),
    ("Ursodeoxicólico"),
    ("Vareniclina"),
    ("Wellbutrin"),
    ("Xanax"),
    ("Yohimbina"),
    ("Zolpidem"),
    ("Alprazolam"),
    ("Benadryl"),
    ("Cetirizina"),
    ("Diazepam"),
    ("Efedrina"),
    ("Fenitoína");

-- Descripciones de medicamentos
INSERT INTO descripciones_medicamentos (descripcion, medicamento_id)
VALUES
    ("Antiviral utilizado en el tratamiento del herpes.", 1),
    ("Analgésico y antipirético comúnmente conocido como paracetamol.", 2),
    ("Antibiótico de amplio espectro.", 3),
    ("Mucolítico y antioxidante.", 4),
    ("Vitamina C, un antioxidante esencial.", 5),
    ("Vitamina B utilizada en suplementos.", 6),
    ("Antiepiléptico y estabilizador del estado de ánimo.", 7),
    ("Antiparasitario.", 8),
    ("Broncodilatador para el asma.", 9),
    ("Ansiolítico y sedante.", 10),
    ("Antibiótico combinado de amplio espectro.", 11),
    ("Antibiótico de espectro amplio.", 12),
    ("Antiarrítmico para el corazón.", 13),
    ("Antibiótico macrólido.", 14),
    ("Corticosteroide antiinflamatorio.", 15),
    ("Antibiótico de cefalosporina.", 16),
    ("Antibiótico de cefalosporina.", 17),
    ("Antibiótico de quinolona.", 18),
    ("Corticosteroide antiinflamatorio.", 19),
    ("Antiinflamatorio no esteroideo.", 20),
    ("Medicamento para la insuficiencia cardíaca.", 21),
    ("Antibiótico y antiinflamatorio.", 22),
    ("Ansiolítico y sedante.", 23),
    ("Antiinflamatorio y protector gástrico.", 24),
    ("Medicamento para la insuficiencia cardíaca.", 25),
    ("Inotrópico para el corazón.", 26),
    ("Inhibidor de la ECA para la hipertensión.", 27),
    ("Implante anticonceptivo.", 28),
    ("Anticonvulsivo.", 29),
    ("Antifúngico.", 30),
    ("Antidepresivo.", 31),
    ("Antiepiléptico y analgésico.", 32),
    ("Hipoglucemiante oral.", 33),
    ("Hipoglucemiante oral.", 34),
    ("Anticoagulante.", 35),
    ("Antiinflamatorio no esteroideo.", 36),
    ("Antidepresivo tricíclico.", 37),
    ("Hormona para el control de azúcar en sangre.", 38),
    ("Antibiótico de quinolona.", 39),
    ("Antihistamínico.", 40),
    ("Hipoglucemiante oral.", 41),
    ("Betabloqueante para la presión arterial.", 42),
    ("Analgésico opiáceo.", 43),
    ("Antiinflamatorio no esteroideo.", 44),
    ("Bloqueante de canales de calcio.", 45),
    ("Inhibidor de la bomba de protones para el estómago.", 46),
    ("Analgésico y antipirético.", 47),
    ("Corticosteroide antiinflamatorio.", 48),
    ("Betabloqueante para el corazón.", 49),
    ("Antibiótico para la tuberculosis.", 50),
    ("Broncodilatador para el asma.", 51),
    ("Antidepresivo.", 52),
    ("Estatina para reducir el colesterol.", 53),
    ("Broncodilatador y estimulante respiratorio.", 54),
    ("Antiepiléptico y estabilizador del estado de ánimo.", 55),
    ("Anticoagulante.", 56),
    ("Antidepresivo.", 57),
    ("Ansiolítico y sedante.", 58),
    ("Antihipertensivo.", 59),
    ("Antibiótico.", 60),
    ("Antiemético.", 61),
    ("Antidepresivo.", 62),
    ("Antagonista del receptor H2.", 63),
    ("Broncodilatador.", 64),
    ("Relajante de músculos de la próstata.", 65),
    ("Antidepresivo.", 66),
    ("Anticoagulante oral.", 67),
    ("Anticonceptivo oral.", 68),
    ("Hipnótico.", 69),
    ("Antidepresivo tricíclico.", 70),
    ("Ansiolítico.", 71),
    ("Ansiolítico y antiepiléptico.", 72),
    ("Antitusivo.", 73),
    ("Inhibidor de la bomba de protones.", 74),
    ("Diurético.", 75),
    ("Antibiótico aminoglucósido.", 76),
    ("Diurético tiazídico.", 77),
    ("Antifúngico.", 78),
    ("Antiinflamatorio no esteroideo.", 79),
    ("Inhibidor de la bomba de protones.", 80),
    ("Antibiótico.", 81),
    ("Antiinflamatorio no esteroideo.", 82),
    ("Antipsicótico.", 83),
    ("Inhibidor de la bomba de protones.", 84),
    ("Antipsicótico.", 85),
    ("Antipsicótico.", 86),
    ("Inhibidor de la fosfodiesterasa tipo 5.", 87),
    ("Inhibidor de la fosfodiesterasa tipo 5.", 88),
    ("Colerético y colagogo.", 89),
    ("Ayuda para dejar de fumar.", 90),
    ("Antidepresivo.", 91),
    ("Ansiolítico.", 92),
    ("Afrodisíaco.", 93),
    ("Hipnótico.", 94),
    ("Ansiolítico.", 95),
    ("Antihistamínico.", 96),
    ("Antihistamínico.", 97),
    ("Ansiolítico.", 98),
    ("Descongestionante.", 99),
    ("Antiepiléptico.", 100);
    
    CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);